elastic/opentelemetry-demo

.github/README.md

Fixing a typo

---

.github/workflows/build-images-elastic.yml

Fixes the workflow path, see issue: https://github.com/elastic/opentelemetry-demo/actions/runs/9577334213
It will also trigger the workflow for pull requests and merges to main, thus we ensure images can always be build.

ci: fix image components path

---

.github/workflows/merge-upstream.yaml

Auto rebase rewrites commit history, thus removing references to current tags

ci: switch to auto merge strategy

---

.env.override
.github/workflows/component_build-images-elastic.yml

- Fix frauddetectionservice Dockerfile path for building the images
- Override custom Dockerfiles path
~~* [ ] `CHANGELOG.md` updated to document new feature additions~~
~~* [ ] Appropriate documentation updates in the [docs][]~~
~~* [ ] Appropriate Helm chart updates in the [helm-charts][]~~

ci: add fraud service Elastic Dockerfile's path

---

.github/workflows/component_build-images-elastic.yml

Fix email service context path

ci: fix email service context path

---

src/frauddetectionservice/Dockerfile.elastic

Aligns download and usage path

fix: fraud service Java agent path

---

kubernetes/elastic-helm/configmap-elastic.yaml

add environment configuration to the collector

---

kubernetes/elastic-helm/configmap-daemonset.yaml

enable k8s.pod.memory.node.utilization metric

---

kubernetes/elastic-helm/daemonset.yaml

feat: add rules for kubelet node metrics

---

.env.override
kubernetes/elastic-helm/deployment.yaml

chore: bump demo images to release 1.11.2

---

kubernetes/elastic-helm/configmap-deployment.yaml

fix: add explicit env keyword

---

kubernetes/elastic-helm/daemonset.yaml
kubernetes/elastic-helm/deployment.yaml

Configuration is created and added to the arguments by the Helm Chart.

chore: remove unused configuration files

---

.env.override
kubernetes/elastic-helm/deployment.yaml

chore: bump demo images version

---

kubernetes/elastic-helm/configmap-daemonset.yaml

fix: k8s collector logs path

---

.github/README.md

Change to a more accurate cd command

---

.github/README.md

Fixes links from .github/README.md

---

scripts/rca-demo/setup

Fix env file path

---

.env.override
kubernetes/elastic-helm/deployment.yaml

bump to demo 1.11.5

---

.github/README.md
src/otelcollector/otelcol-elastic-config.yaml

Adds hostmetrics receiver metrics for local deplyment

feat: enable hostmetrics for local deployment

---

.github/workflows/component_build-images-elastic.yml

fix: flagd-ui image path

---

.env.override
kubernetes/elastic-helm/deployment.yaml

bump demo images version to 2.0.1

---

.github/README.md

Adding a section about testing custom OTel collector components
I will not be available for following up on this, so please change whatever needed and bring to merge if you think this section is useful. I went through the process of figuring this out in the last two days, so I think it can be very useful to others

Adding testing section to README.md

---

kubernetes/elastic-helm/daemonset.yaml
kubernetes/elastic-helm/deployment.yaml
src/otel-collector/otelcol-elastic-config.yaml

add lsminterval 60min aggregations

---

.env.override
kubernetes/elastic-helm/daemonset.yaml
kubernetes/elastic-helm/deployment.yaml

rollback to elastic-agent 8.17.2 version

---

.env.override
kubernetes/elastic-helm/demo.yml

Bump release version to 2.0.3

---

.env.override
kubernetes/elastic-helm/demo.yml

Bump demo version and elastic stack version

---

.github/README.md
kubernetes/elastic-helm/demo.yml

Fixes https://github.com/elastic/opentelemetry-demo/issues/151

disable load-generator browser traffic

---

.env.override
.github/README.md
docker-compose.yml
src/otel-collector/otelcol-elastic-config.yaml

- closes https://github.com/elastic/opentelemetry-demo/issues/154

Update EDOT version to 9.1.0
