- .github/README.md
These render when looking at [.github/README.md](https://github.com/elastic/opentelemetry-demo/tree/main/.github) but not on the more commonly viewed https://github.com/elastic/opentelemetry-demo/tree/main - fixes the latter at the expense of the former
> fix paths to images in README

- .github/README.md
Reverts elastic/opentelemetry-demo#5
This seems to have been fixed on the GH side, at least it works in [this preview](https://github.com/graphaelli/opentelemetry-demo/tree/revert-5-fix-readme-images)
> Revert "fix paths to images in README"

- src/otelcollector/otelcol-config-extras.yml
The filter processor was previously deleted but still lingering in the config
> Remove invalid `filter` processor

- .github/README.md
- src/adservice/Dockerfile.elastic
- src/frauddetectionservice/Dockerfile.elastic
Add Elastic Dockerfiles (Dockerfile.elastic) that uses the Elastic's Java agent distribution for the Ad and Fraud detection services. Those Dockerfiles are a copy of the upstream version but replacing the Java agent.
The idea is to later [parametrize](https://github.com/elastic/opentelemetry-demo/blob/main/docker-compose.yml#L223) the `Dockerfile` file used in the `docker-compose.yml` to point to our custom Dockerfile using the new [.env.override file](https://github.com/elastic/opentelemetry-demo/blob/main/.env.override).
- Dependabot will be configured in a future PR to maintain the agent version up-to-date.
- Modify the Dockerfile used in the upstream version:
- Pros: no need to make to parametrize Dockerfile (upstream changes)
- Cons:
- Merge conflicts
For new features contributions …
> add Java Elastic distribution for Ad and Fraud services

- .github/README.md
- src/cartservice/src/Directory.Build.props
- src/cartservice/src/Program.cs
Add .NET Elastic's distribution as a drop-in replacement to the upstream version.
> add OpenTelemetry .NET Elastic's distribution

- .env.override
Override image environment variable to point latest custom images: ghcr.io/elastic/opentelemetry-demo
> override demo images environment variables

- src/adservice/Dockerfile.elastic
- src/frauddetectionservice/Dockerfile.elastic
Bump Elastic Java agent, see: https://github.com/elastic/elastic-otel-java/releases/tag/v0.4.0
> chore: bump Java agent to 0.4.0

- .env.override
- .github/README.md
- docker-compose.minimal.yml
- docker-compose.yml
- kubernetes/elastic-helm/configmap-elastic.yaml
- kubernetes/elastic-helm/values.yaml
- src/otelcollector/otelcol-config-extras.yml
- src/otelcollector/otelcol-elastic-config-extras.yaml
- src/otelcollector/otelcol-elastic-config.yaml
Replace the Contrib collector with the Elastic distribution:
Note that the `elasticsearch exporter` has not been added yet to the configuration pipelines. For the moment, the configuration still uses the Otlp endpoint to forward all the logs, traces and metrics.
> add the Elastic Collector distribution

- kubernetes/elastic-helm/configmap-daemonset.yaml
- kubernetes/elastic-helm/deployment.yaml
Adds the `k8s.node.name` resource attribute (among others) to all the APM services, this will be used as hostname by the apm server.
> add K8s resoure attributes to apm services

- src/adservice/Dockerfile.elastic
- src/cartservice/src/Directory.Build.props
- src/frauddetectionservice/Dockerfile.elastic
- src/kafka/Dockerfile.elastic
- src/paymentservice/package-lock.json
- src/paymentservice/package.json
> chore: bump Elastic agent distributions

- .env.override
- docker-compose.minimal.yml
- docker-compose.yml
- kubernetes/elastic-helm/configmap-daemonset.yaml
- kubernetes/elastic-helm/configmap-deployment.yaml
- kubernetes/elastic-helm/daemonset.yaml
- kubernetes/elastic-helm/deployment.yaml
Use 8.16.0-SNAPSHOT version so we can remove the entrypoint override.
> chore: bump elastic-agent to 8.16.0-SNAPSHOT

- docker-compose.yml
- src/kafka/Dockerfile.elastic
- src/otelcollector/otelcol-elastic-config.yaml
Neither were working right, in the case of kafka this disables some problematic tracing options and in the case of the collector this fixes the config yaml
> Fix Kafka and Collector config for macs

- .github/README.md
Fixing incorect instructions on the node-level metrics. Omitting the `https`prefix didn't work when I tried to deploy.
You may want to test this on your end. I was unable to get my GKE cluster working without adding the https prefix to the secret.
> Fix incorrect instructions for Node level metrics collection

- .github/README.md
Be explicit about cloning the repo and the working directory.
> Clarify install instructions

- kubernetes/elastic-helm/deployment.yaml
Disables traces in the product catalog service as documented already in the README
> Disable spans on product catalog service in k8s

- .github/README.md
- kubernetes/elastic-helm/deployment.yaml
- src/otelcollector/otelcol-elastic-config-extras.yaml
This is a simple change to remove the "Bearer" hardcoding so that the otel demo works properly for serverless, the README has also been updated to reflect this change.
> Change the authentication method to work with Elastic Serverless

- elastic-setup
- scripts/rca-demo/setup
- trigger-demo-scenario
If the new ./scripts/rca-demo/.env file has been created (copied from the .env.example file), the setup script will auto-source it. 
Also, the old locations for the elastic-setup and trigger-demo-scenario scripts now tell you where they have been moved.
> Auto sources .env file if it exists

- scripts/rca-demo/.env.example
- scripts/rca-demo/setup
@andrewvc earlier today made the actual installation of synthetics dependent on the SYNTHETICS_API_KEY value being non-empty. These changes adjust the corresponding .env.example documentation as well as the gated requirements checking during the setup script run.
Before these changes, the setup script will fail if you don't set all of the env vars, even ones only needed for synthetics setup.
> Makes synthetics requirements optional

- kubernetes/elastic-helm/deployment.yaml
- scripts/rca-demo/create-release-annotation
- scripts/rca-demo/setup
We need to set `tls.insecure: true` for local APM server and local ES when working with local setup. This PR adds an argument to be passed to `setup` script called `local` which will add `tls` setting to `deployment.yaml` and `daemonset.yaml` files. It will also check if `tls` setting is present when not running `local` setup and warn user about it.
This PR also adds a script to Create release/rollback annotations.
> TLS setting for local setup and create annotation script

- scripts/rca-demo/create-release-annotation
- scripts/rca-demo/trigger-demo-scenario
Changes related to version release annotation script:
- Pass service name as argument to `create-release-annotation` script
- Call `create-release-annotation` script with `-s cartservice` in `trigger-demo-scenario` script as this script uses `cartservice` (If needed, we can make `trigger-demo-scenario` script to accept service name as argument)
- Run the scripts from `opentelemetry-demo` folder
```
./scripts/rca-demo/create-release-annotation -s checkoutservice
./scripts/rca-demo/create-release-annotation restore -s checkoutservice
./scripts/rca-demo/trigger-demo-scenario
./scripts/rca-demo/trigger-demo-scenario restore
```
> Pass service name as argument to version release annotation script

- scripts/rca-demo/README.md
- scripts/rca-demo/data/mapping-message-alias.json
- scripts/rca-demo/data/rule-01.json
- scripts/rca-demo/post-setup
- scripts/rca-demo/setup
- scripts/rca-demo/shared.sh
- Removes unnecessary prerequisites from scripts/rca-demo/README.md
- Adds post-setup script to set things up in Kibana and ES after the initial app setup
- Moves some shared logic from the initial setup script into a shared.sh file that can be sourced by all scripts
> Adds more scripts for post-setup

- scripts/rca-demo/trigger-demo-scenario
Improves the scenario by not requiring a scaledown before switching the entrypoint. This means the LLM doesn't sense the scaledown as a reason
> Improved demo trigger

- .gitignore
- scripts/rca-demo/.env.example
- scripts/rca-demo/README.md
- scripts/rca-demo/autosource.sh
- scripts/rca-demo/create-release-annotation
- scripts/rca-demo/data/data_view-01.json
- scripts/rca-demo/data/rule-01.json
- scripts/rca-demo/post-setup
- scripts/rca-demo/setup
- scripts/rca-demo/shared.sh
`post-setup` should now work properly, but you will need to pay attention to the env vars that are required in .env.example
I've removed KIBANA_API_KEY and replaced it with KIBANA_USER and KIBANA_PASSWORD because I think they will be more reliable and easier to reason about (the EEM enablement PUT request fails with the API key but works with the user/pass).
I've also removed the synthetics setup stuff from the main setup script, as @andrewvc has gotten synthetics up and running using a different path. We can revisit that later.
> Finalizes post-setup script and updates docs

- scripts/rca-demo/post-setup
The OTel demo seems to have updated so that its otel logs no longer ship with `body_text`, which we had to account for before, but now with `body.text`, which our mappings already account for. So the post-setup script will break our ES env with this mapping change, if the data is flowing in with body.text. We no longer need this mapping update, unless you're running an old version of the OTel demo services. 
If you still see body_text in your logs-*otel* documents, kill minikube and re-run the `setup` script, and it should start sending documents with body.text instead.
> Removes body text alias mapping change because OTEL demo updated

- kubernetes/elastic-helm/daemonset.yaml
- kubernetes/elastic-helm/deployment.yaml
Always pull the elastic agent image for the daemonset
> Always pull elastic-agent image for daemonset

- kubernetes/elastic-helm/deployment.yaml
This fixes a typo in the loadgenerator deployment config, that was causing all tasks for the WebsiteUser to fail (the ones for WebsiteBrowserUser are working). Looks like that gives us logs for at least 6 more services:
- `accountingservice`
- `emailservice`
- `paymentservice`
- `quoteservice`
- `shippingservice`
- `valkey`
> Fix typo for LOCUST_HOST

- scripts/rca-demo/create-release-annotation
Resolves https://github.com/elastic/opentelemetry-demo/issues/117
Removes `jq` dependency from `create-release-annotation` script
> Remove jq dependency from create-release-annotation script

- .github/workflows/component_build-images-elastic.yml
- src/cartservice/src/Directory.Build.props
- src/paymentservice/package-lock.json
- src/paymentservice/package.json
Adds the new flagd-ui service into the build images file and bumps Elastic dotnet and nodeJS agents image.
> chore: add flagd-ui image and bump Elastic agents

- .github/workflows/component_build-images-elastic.yml
> fix: load .env during images build

- .env.override
- kubernetes/elastic-helm/daemonset.yaml
- kubernetes/elastic-helm/deployment.yaml
> chore: bump otel-demo to 8.16.0

- .github/README.md
- kubernetes/elastic-helm/daemonset-otlp.yaml
- kubernetes/elastic-helm/deployment-otlp.yaml
- src/otel-collector/otelcol-elastic-otlp-config.yaml
This PR introduces support for the Managed Ingest Endpoint using otlphttp exporters. It serves as a temporary solution until a more streamlined approach is implemented upstream (ref: [opentelemetry-demo#2052](https://github.com/open-telemetry/opentelemetry-demo/issues/2052)).
The Kubernetes and Docker Compose configurations are adapted from existing setups that use the Elasticsearch exporter.
- relates to https://github.com/elastic/opentelemetry-dev/issues/621
> Add support for Managed Ingest Endpoint

- src/cart/src/Program.cs
- src/cart/src/cart.csproj
The current cart code (`AddOpenTelemetry`) registers using the vanilla SDK, not EDOT. In early alphas, we intercepted this and registered EDOT, but we decided to make it an explicit choice.
This PR updates the registration to use the EDOT API, reducing the boilerplate code required. EDOT also brings in a set of transitive dependencies, so I've removed the explicit package references for those from the project file.
> Register the EDOT (not vanilla SDK)

- .env.override
A few EDOT collector components were removed with 9.0.0:
```
Starting in otel mode
failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
error decoding 'processors': unknown type: "lsminterval" for id: "lsminterval" (valid values: [resource transform resourcedetection memory_limiter elastictrace batch attributes filter geoip k8sattributes elasticinframetrics])
error decoding 'connectors': unknown type: "signaltometrics" for id: "signaltometrics" (valid values: [routing spanmetrics elasticapm])
``` …
> rollback elastic-agent docker override version to 8.17.4

- .env.override
- .github/README.md
- demo.sh
- kubernetes/elastic-helm/demo.yml
- src/otel-collector/otelcol-elastic-otlp-config.yaml
This PR introduces a script that automates the deployment of demo applications and EDOT, with configurations and wiring already in place. The only required input is Elastic credentials, streamlining the demo launch process.
The original manual configuration remains intact and can still be followed, especially if users prefer to provide a custom OTel Collector configuration.
> Add wrapper bash script to deploy the demo

- .github/README.md
- demo.sh
The current K8s installation process for always installs the latest version of the Opentelemetry Demo Helm Charts. This can cause inconsistencies when our fork is not fully up-to-date with upstream (see https://github.com/elastic/opentelemetry-demo/issues/168). 
This PR add a version pin to ensure to install a compatible version of the charts (at this time, 0.37.8)
It also updates the version of the our kube stack to `0.10.5`, to include this fix https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1877
> [k8s] Pin upstream demo helm version
